### PR TITLE
Fix image rendering in volunteer quizzes

### PR DESCRIPTION
**Pull request by joncancode**
this one should be for https://github.com/UPchieve/web/pull/140 - i made a new local branch by mistake and did it from there

i created a new branch and added a little more, including @lualparedes  overflow-y: auto mention and fixing the margins and button placement from @alymurray

### CODE REVIEW

**Comment by lualparedes** [comment]
I understand that this was initially only meant to solve #132 but as it organically evolved into a refactoring endeavor (which is acknowledged in the very name :joy:), then I'm gonna base my observations on that perspective:
- Refactoring branches are `fix/` branches [by definition](https://github.com/UPchieve/web/blob/master/docs/git-workflow.md#naming-convention). Leave this one with its current name, but keep this in mind for the future.
- Aly's requests 1 and 2 (see figure 1) were fulfilled successfully
  > Fig 1
  > *Figure 1*
- Aly's request 3 was not fulfilled (I'm assuming that she meant that she wanted those elements to be *absolutely positioned* to the bottom), however, I like the new version better because it's more robust and more visually cohesive. I mark it with a "?" because I leave it up to @alymurray to approve it.
- Aly's request 4 was not fulfilled. If you look closely, you'll notice that the red scrollbar only spans the middle element, but the scroll in the current version is still handled by the container.
- Aly's request 5 was partially fulfilled (see figure 2). This issue is related to the previous one, and both of them can be solved by using a similar strategy as the one used for the Specs modal in [this page](https://lual-production.firebaseapp.com/) (open the modal by clicking on "Specs" in the footer, you should see something like fig. 3 in a small screen).
  > Fig 2
  > *Figure 2*

  > Fig 3
  > *Figure 3* - The scroll in the modal is handled by the element in the middle.
- [Remember to lint](https://github.com/UPchieve/web/blob/master/docs/coding-standards/README.md#javascript) using `npx eslint <path/to/file>` and make sure to solve all the issues before submitting the code:
  ```
    /home/lual/Desktop/projects/upchieve-frontend/src/components/Quiz.vue
    20:1  error  Expected indentation of 4 spaces but found 8 spaces    vue/html-indent
    21:1  error  Expected indentation of 6 spaces but found 4 spaces    vue/html-indent
    22:1  error  Expected indentation of 8 spaces but found 6 spaces    vue/html-indent
    23:1  error  Expected indentation of 8 spaces but found 6 spaces    vue/html-indent
    24:1  error  Expected indentation of 8 spaces but found 6 spaces    vue/html-indent
    25:1  error  Expected indentation of 10 spaces but found 8 spaces   vue/html-indent
    26:1  error  Expected indentation of 12 spaces but found 10 spaces  vue/html-indent
    27:1  error  Expected indentation of 12 spaces but found 10 spaces  vue/html-indent
    28:1  error  Expected indentation of 12 spaces but found 10 spaces  vue/html-indent
    29:1  error  Expected indentation of 12 spaces but found 10 spaces  vue/html-indent
    30:1  error  Expected indentation of 8 spaces but found 6 spaces    vue/html-indent
    31:1  error  Expected indentation of 8 spaces but found 6 spaces    vue/html-indent
    32:1  error  Expected indentation of 8 spaces but found 6 spaces    vue/html-indent
    33:1  error  Expected indentation of 10 spaces but found 8 spaces   vue/html-indent
    34:1  error  Expected indentation of 10 spaces but found 8 spaces   vue/html-indent
    35:1  error  Expected indentation of 10 spaces but found 8 spaces   vue/html-indent
    36:1  error  Expected indentation of 6 spaces but found 4 spaces    vue/html-indent
    38:1  error  Expected indentation of 6 spaces but found 10 spaces   vue/html-indent
    39:1  error  Expected indentation of 8 spaces but found 6 spaces    vue/html-indent
    40:1  error  Expected indentation of 8 spaces but found 6 spaces    vue/html-indent
    552:9  error  Newline required at end of file but not found          eol-last

    /home/lual/Desktop/projects/upchieve-frontend/src/components/Sidebar.vue
       3:27  error  Attribute "to" should be on a new line         vue/max-attributes-per-line
      22:25  error  Strings must use singlequote                   quotes
      24:21  error  Strings must use singlequote                   quotes
      25:25  error  Strings must use singlequote                   quotes
      26:20  error  Strings must use singlequote                   quotes
      32:26  error  Missing trailing comma                         comma-dangle
      36:34  error  Missing trailing comma                         comma-dangle
      38:4   error  Missing trailing comma                         comma-dangle
      90:9   error  Newline required at end of file but not found  eol-last

    ✖ 30 problems (30 errors, 0 warnings)
      30 errors and 0 warnings potentially fixable with the `--fix` option.
  ```

**Comment by alymurray** [comment]
**Picture 1: master branch**
image

vs.

**Picture 2: feat/refactor branch**
image

I personally think Picture 1 looks better. However, currently when the window is too short it looks like this:

**Picture 3: master branch**
image

Instead of like this:

**Picture 4: feat/refactor branch**
image

Which is definitely not ideal. Can we make it look like Picture 1 when the window is big enough but Picture 4 when the window is too small?

**Comment by alymurray** [comment]
Also noticing it looks kind of weird when the window is very wide now

image

**Comment by alymurray** [comment]
"You failed" message is missing

image

**Comment by alymurray** [comment]
image

1. Image is still getting cut off a tiny bit it looks like? Is this true whenever the image is greater than a certain size?
2. Can we move the "previous" button to always be left-aligned to the navigation box at the bottom? And "next" button always right-aligned (which it is now, even on the first question, so great job on that!)

**Comment by alymurray** [comment]
Ok so @joncancode it looks MUCH better overall, great job!! The only changes that I think are necessary before we merge in the branch are:
1. Get the "You passed! / You failed." messages back
2. Left align the "previous button"
3. Answer my question about image sizing so I know how often it will still get cut off and by how much.

**Comment by joncancode** [comment]
Hey @alymurray what would you think about having the buttons like the following:

**QUIZ BUTTONS**
screen shot 2019-02-16 at 5 29 34 pm
When there is just one button, it appears in the middle

screen shot 2019-02-16 at 5 29 21 pm
when there are two, it's spaced evenly.

I think this may make it look a little better, since when the window is made larger like you mentioned before, having the next button too far to the right looks a little bad. Let me know what you think!

**QUESTION IMAGES**
One other thing about the question images. I think the best solution is to re-upload these in a better way. For example, see the following pictures:

screen shot 2019-02-16 at 5 33 10 pm
screen shot 2019-02-16 at 5 32 47 pm

These are two images in use. One is easy to see here. It's a white background with an image inside. The other (harder to see), is a much smaller image because it does not have that same background. So when it is in use during the quiz, it's cropped much differently from the one with the white background. I think re-doing these may be the best solution here. Let me know what you think. I can definitely help with that.

**Comment by jmromer** [comment]
This branch is now up-to-date with master, but it's still WIP as it appears to introduce regressions.

### master

Screen Shot 2019-03-25 at 4 01 14 PM

### feat/refactor

Screen Shot 2019-03-25 at 3 59 27 PM

**Pull request closed without merging**
