### PR TITLE
Read-only whiteboard on session end

### PR DESCRIPTION
**Pull request by jkeat**
Description
-----------
- Make whiteboard read-only on session end
- Fixes issue caused by interacting with whiteboard that had been cleared from the server's doc cache

Developer self-review checklist
-------------------------------
- [ ] Potentially confusing code has been explained with comments
- [ ] No warnings or errors have been introduced; all known error cases have been handled
- [ ] Any appropriate documentation (within the code, README.md, docs, etc) has been updated
- [ ] All edge cases have been addressed

### CODE REVIEW

**Review by treykris — APPROVED** [review]
Nice, looks good!

**Comment by treykris** [comment]
Update: If I backspace after the session ends and rejoin it by using the forward button, I'm able to write on the whiteboard - not sure if still intended

**Comment by jkeat** [comment]
> Update: If I backspace after the session ends and rejoin it by using the forward button, I'm able to write on the whiteboard - not sure if still intended

You don't get the modal saying "Session Fulfilled; This session has already finished" ?

**Comment by treykris** [comment]
Ah, I was clicking outside of the modal and then writing on the whiteboard. I'm thinking we should make those modals not be able to close outside of the clicking the action button. I think I changed the behavior when we were rethinking the modal situation

**Pull request merged**
