### PR TITLE
Admin dashboard

### PR DESCRIPTION
**Pull request by georgiagallant333**
Links
-----
- Task: https://www.notion.so/upchieve/Create-admin-dashboard-c4f61523c3284666b7fae3b309b3bbe5
- Server repo PR: https://github.com/UPchieve/server/pull/110#issue-298609551

Description
-----------
Creates an empty admin dashboard (with two buttons for metrics and edu admin), but allows capability to add more dashboards. 

Developer self-review checklist
-------------------------------
- [x] Task's requirements have been fully addressed
- [x] Potentially confusing code has been explained with comments
- [x] Posted a link to this PR on the Notion task
- [x] No warnings or errors have been introduced; all known error cases have been handled
- [x] Any appropriate documentation (within the code, README.md, docs, etc) has been updated
- [x] There are no new spelling/grammar mistakes in the UI, code, or documentation
- [x] Branch has been deployed to staging, and all edge cases have been manually tested (on multiple browsers)
- [x] All new code complies with our ESLint standards

### CODE REVIEW

**Comment by jkeat** [comment]
@georgiagallant333 check out the changes I just pushed ^ and lmk if that all makes sense

**Comment by jkeat** [comment]
@georgiagallant333 couple little things about this PR that we should discuss, let's talk tomorrow!

**Comment by jkeat** [comment]
@georgiagallant333 just to confirm, can safely I delete this branch?

**Comment by georgiagallant333** [comment]
as long as it won’t impact branches that branched from this one then yeah!

**Pull request closed without merging**
