### PR TITLE
Session e2e tests

### PR DESCRIPTION
**Pull request by jkeat**
Links
-----
- Issue: https://github.com/UPchieve/web/issues/310

Description
-----------
- Add e2e tests for sessions

Developer self-review checklist
-------------------------------
- [x] Potentially confusing code has been explained with comments
- [x] No warnings or errors have been introduced; all known error cases have been handled
- [x] Any appropriate documentation (within the code, README.md, docs, etc) has been updated
- [x] All edge cases have been addressed

### CODE REVIEW

**Comment by jkeat** [comment]
Let me know if any of these are failing for you guys! Might need to be more generous with some of the `cy.wait(...)` timeouts.

Note: make sure your local volunteer test user is certified in essays

**Comment by treykris** [comment]
@jkeat,

I ran the tests a few times and the main culprits that I came across were:
- [Timed out] - Should log out successfully
- [Timed out] - Should return to dashboard during active sessions

I added a pretty generous explicit wait (`cy.wait(10000)`) for  `Should log out successfully` to pass without any errors. Do you have any thoughts on explicit waits vs implicit waits for requests? 

> Note 2: I've seen issues related to un-ended sessions from previously failed tests that get in the way of later tests. If this turns out to be a big issue, we might want to add a utility that can clear out all of a given user's active sessions.

I've come across this issue a few times when running the tests

**Comment by jkeat** [comment]
@treykris When you get a chance, can you try running these again and let me know if you're still having issues?

**Comment by treykris** [comment]
@jkeat,

Fixed the issues on my side, tests are running!

**Pull request merged**
