### PR TITLE
Fix: Re-join users automatically after connections are re-established, and warn if disconnected.

### PR DESCRIPTION
**Pull request by dmnisson**
Links
-----
Task: https://www.notion.so/upchieve/Chat-and-whiteboard-do-not-update-after-a-previously-broken-connection-is-re-established-5b82a2c25cfd4e519a8d5aa8bf8e7ff1

Description
-----------
Add a message to alert the user if there is a problem with the connection between client and server during a session (the socket connection). This is also a fix for a bug that causes the user to not be back in the session even after a connection is re-established.

If a student and volunteer do the following:

1. Student begins a session
2. Volunteer accepts the session
3. Either student or volunteer disconnects from the network, or the server shuts down
4. The connection comes back online

The users whose connections were broken and then re-established will not be able to see messages being sent, or whiteboard drawings being drawn, until they refresh the page. There is currently no indication that the user must do this.

This behavior occurs because, in a session, the socket events are not sent directly to individual users, but instead are sent to "rooms" that the users must join to receive them. Although Socket.IO includes a mechanism to automatically re-establish broken connections, it does not, by default, put users back into rooms that they were in before the connection was broken.

This PR fixes this behavior by automatically re-joining users in response to Socket.IO automatically re-establishing the connection. Now, when a connection is disconnected and re-established, the client will join the session automatically. The previously disconnected user will see messages that the other user sent to the server while the connection was down, and will be able to receive and send messages without any further action.

I also added a message to the header warning users when a connection is broken and including a "Try Now" button to attempt to re-establish the connection manually.

When only one user in a session is disconnected, we may also want to provide an ephemeral notification to alert the other user that their messages and whiteboard drawings may not be received right away.

Developer self-review checklist
-------------------------------
- [x] Task's requirements have been fully addressed
- [x] PR link has been posted in the task's comments
- [x] Potentially confusing code has been explained with comments
- [x] No warnings or errors have been introduced; all known error cases have been handled
- [x] Any appropriate documentation (within the code, README.md, docs, etc) has been updated
- [x] There are no new spelling/grammar mistakes in the UI, code, or documentation
- [x] Branch has been deployed to staging, and all edge cases have been manually tested
- [x] Task and PR have been updated to show that this is ready for review

### CODE REVIEW

**Comment by jkeat** [comment]
@dmnisson can you look into the new merge conflicts? they're all probably pretty minor

(i'm copy-pasting this message a lot due to the recent merge of Justin's restructuring PR 😄)

**Comment by dmnisson** [comment]
> @dmnisson can you look into the new merge conflicts? they're all probably pretty minor
> 
> (i'm copy-pasting this message a lot due to the recent merge of Justin's restructuring PR 😄)

Conflicts have been resolved.

**Comment by jkeat** [comment]
@dmnisson i sound like a broken record 😌 but could you take a look at the merge conflicts?

**Comment by dmnisson** [comment]
> @dmnisson i sound like a broken record 😌 but could you take a look at the merge conflicts?

The conflicts have been resolved.

**Pull request merged**
