### PR TITLE
Add Docker Support

### PR DESCRIPTION
**Pull request by ti2ger92**
Description
-----------
- _This adds Docker support, and instructions to use it_

### CODE REVIEW

**Comment by jkeat** [comment]
@ti2ger92 Hmm, the CircleCI build seems to be stuck

**Comment by ti2ger92** [comment]
Any idea how to get it to restart? I haven't been able to get it to do that yet.

**Comment by jkeat** [comment]
@ti2ger92 I think CircleCI might be having issues because the PR's source branch is under your personal account (`ti2ger92:master`) as opposed to a branch pushed to this repo

**Comment by ti2ger92** [comment]
Hmm, if true that would be an issue, as this was the only way to work with UPchieve until you added me. I can look into verifying that.

**Comment by jkeat** [comment]
> Hmm, if true that would be an issue, as this was the only way to work with UPchieve until you added me. I can look into verifying that.

Ah, good point -- @alymurray  we should consider changing our permissions to allow anyone to push a branch to the web & server repos. The master branches are already protected, but I'd need to make sure we require an admin review to merge.

**Comment by alymurray** [comment]
I'm fine with you making that change as long as you also make the admin review required to merge!

**Pull request merged**
