### PR TITLE
log error when portal gun is unavailable

### PR DESCRIPTION
**Pull request by treykris**
Description
-----------
- Catch error from Portal Gun methods being called when it's unavailable

Developer self-review checklist
-------------------------------
- [x] Potentially confusing code has been explained with comments
- [x] No warnings or errors have been introduced; all known error cases have been handled
- [x] Any appropriate documentation (within the code, README.md, docs, etc) has been updated
- [x] All edge cases have been addressed

### CODE REVIEW

**Comment by treykris** [comment]
@jkeat , @austinhallock 

Was curious to know if it's okay just to log it? Are empty catch statements acceptable?

**Comment by jkeat** [comment]
Yeah this seems okay to me

**Comment by austinhallock** [comment]
sorry, just saw this. i'd probably just catch here https://github.com/UPchieve/web/blob/master/src/services/PortalService.js#L15 instead

**Comment by treykris** [comment]
@austinhallock 

Sorry, I got sidetracked! I tried that initially, but then this error was popping on when I put a catch  statement 🙁

```
call(method, data) {
    return (
      this.portal
        .call(method, data)
        // eslint-disable-next-line no-console
        .catch(() => console.log("Portal Gun is unavailable."))
    );
  }
```

I'm not too sure how to handle it

Screen Shot 2020-05-08 at 12 41 38 PM

**Comment by austinhallock** [comment]
oh, yeah that would pass null/undefined (whatever console.log returns) to handlePortalData. so then it's trying to get the `path` of undefined.

i'd probably still have the catch inside of the call method (that's what i do for freeroam), then in cases like the handlePortalData, either check `if (data && data.path)` or put a catch in there

**Comment by treykris** [comment]
Updated!

@austinhallock,
Thank you! I totally glossed over the `handlePortalData` function

**Pull request merged**
